### ISSUE TITLE
Line 261, enclave opens.txt

### ISSUE THREAD

**Issue by ReimeiSky** [Makuta-Miras/The-Enclave#21]
On line 261, we have

> `"Thanks, sir," you reply as Hofmann leaves.`
> "reputation: Pug" = -100
> accept

I think you were trying to make the Pug hostile once this mission starts, but you're doing it wrong. If you do that, the Pug remain [friendly, hostile, depending on your reputation with them before the mission], and instead a

> reputation: Pug

line appears when you finish talking with Hofmann. What you should do is add an `on accept` line somewhere in the mission, and have the reputation line be placed under that.

also, there are a few typos up above, such as an extra space between "outfitters" and "here" on line 254.

**Comment by Storm-Crow01** [comment]
Yeah, I caught the reputation thing on my own earlier; if you check the v0.0.8 branch (The version that I'm working from) you'll find that it's already been fixed. As for the typos, I'll go and find them myself in a bit. Thanks!
